---
docker_package_name: docker
docker_apt_key_url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
docker_apt_repository: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ ansible_distribution_release }} stable
